import { Meta, StoryObj } from "@storybook/react";

import { BrickInputBase } from "brick-ui";

const meta: Meta<typeof BrickInputBase> = {
  title: "General/Atoms/BrickInputBase",
  component: BrickInputBase,
  parameters: {
    docs: {
      // You can leave `page: undefined` to use the default autogenerated docs,
      // which will list each story. Since we also provide AllVariants below,
      // it will show up under the “Docs” tab.
      // page: undefined,
    },
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof BrickInputBase>;

// A “base” set of props so we don’t repeat ourselves below.
const baseArgs = {
  label: "Input Label",
  helpText: "This is a help text for the input.",
  placeholder: "Enter text here...",
  value: "",
  disabled: false,
  errorText: "",
  error: false,
  required: false,
  onChange: (e: React.ChangeEvent<HTMLInputElement>) =>
    console.log(e.target.value),
  onFocus: () => console.log("Input focused"),
  onBlur: () => console.log("Input blurred"),
};

export const BrickInputStory: Story = {
    name: "Brick Inout Base",
  render: () => (
    <div style={{ display: "flex", flexDirection: "column", gap: "1rem", maxWidth: "400px" }}>
      <BrickInputBase {...baseArgs} label={'Default'} />

      <BrickInputBase {...baseArgs} disabled value="I'm disabled" helpText="" />

      <BrickInputBase
        {...baseArgs}
        error
        errorText="This field is required."
        helpText=""
      />

      <BrickInputBase {...baseArgs} required helpText="" />

      <BrickInputBase {...baseArgs} value="Filled input" helpText="" />

      <BrickInputBase {...baseArgs} placeholder="Placeholder text" helpText="" />
    </div>
  ),
  parameters: {
    docs: {
      storyDescription:
        "Below you see every variant (Default, Disabled, With Error, Required, etc.) rendered together for quick visual comparison.",
    },
  },
};